# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests.
name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $GITHUB_ENV
          echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> $GITHUB_ENV
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          ~/.rbenv/bin/rbenv install 3.3.0
          ~/.rbenv/bin/rbenv global 3.3.0
          ruby -v

      - name: Install Bundler and gems
        run: |
          gem install bundler
          bundle install

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: rspec
